[profile.default]
src = "contracts"
out = "out"
libs = ["../lib", "lib"]
test = "test"
script = "scripts"

# Compiler settings
solc_version = "0.8.20"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = true

# Gas price settings
gas_reports = ["*"]

# RPC URLs for different networks
[rpc_endpoints]
xlayer_mainnet = "https://rpc.xlayer.tech"
xlayer_testnet = "https://testrpc.xlayer.tech"
ethereum = "https://eth.llamarpc.com"
sepolia = "https://rpc.sepolia.org"

# Etherscan API keys (add your own if needed)
[etherscan]
xlayer = { key = "${XLAYER_ETHERSCAN_API_KEY}", url = "https://www.oklink.com/api/explorer/v1/xlayer" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
